import { cleanRemark, countryFromRemark } from "./countries";
import type { ParsedNode, VpnProtocol } from "./types";

const PROTO_RE = /^(vless|vmess|ss|trojan|hysteria2|hy2|tuic):\/\/\S+/i;
const PROTOCOLS = new Set<VpnProtocol>(["vless", "vmess", "ss", "trojan", "hysteria2", "tuic"]);
const NETWORKS = new Set(["tcp", "ws", "grpc", "h2", "httpupgrade", "splithttp", "xhttp", "quic"]);
const ALPN_ALLOWED = new Set(["h2", "http/1.1", "http/1.0", "h3", "h3-29"]);

function nodeId(parts: Array<string | number | undefined>): string { return parts.map((p) => String(p ?? "").toLowerCase()).join("|").replace(/[^a-z0-9.|:_-]/g, "").slice(0, 180); }
function decodeHtml(s: string): string { return s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">"); }
function tryB64(s: string): string | null { const clean = s.replace(/\s+/g, ""); if (!/^[A-Za-z0-9+/_=-]+$/.test(clean) || clean.length < 16) return null; try { const normalized = clean.replace(/-/g, "+").replace(/_/g, "/"); const padded = normalized + "=".repeat((4 - (normalized.length % 4)) % 4); return typeof Buffer !== "undefined" ? Buffer.from(padded, "base64").toString("utf8") : decodeURIComponent(Array.from(atob(padded), (c) => "%" + c.charCodeAt(0).toString(16).padStart(2, "0")).join("")); } catch { return null; } }
function parseQuery(search: string): Record<string, string> { const out: Record<string, string> = {}; const q = search.startsWith("?") ? search.slice(1) : search; for (const part of q.split("&")) { if (!part) continue; const eq = part.indexOf("="); const k = eq === -1 ? part : part.slice(0, eq); const v = eq === -1 ? "" : part.slice(eq + 1); try { out[decodeURIComponent(k).trim()] = decodeURIComponent(v).trim(); } catch { out[k.trim()] = v.trim(); } } return out; }
function splitHash(line: string): { body: string; remark: string } { const hash = line.indexOf("#"); return hash === -1 ? { body: line, remark: "" } : { body: line.slice(0, hash), remark: line.slice(hash + 1).trim() }; }
function parseHostPort(authority: string): { host: string; port: number } | null { const v6 = authority.match(/^\[([^\]]+)\]:(\d+)$/); if (v6) return { host: v6[1].trim(), port: Number(v6[2]) }; const last = authority.lastIndexOf(":"); if (last === -1) return null; const host = authority.slice(0, last).trim(); const port = Number(authority.slice(last + 1).trim()); if (!host || !Number.isFinite(port) || port <= 0 || port > 65535) return null; return { host, port }; }
function mapNetwork(type: string | undefined): string { const t = (type || "tcp").trim().toLowerCase(); if (t === "raw") return "tcp"; if (t === "h2") return "h2"; if (t === "httpupgrade") return "httpupgrade"; if (t === "splithttp") return "splithttp"; if (t === "xhttp") return "xhttp"; return t; }
function boolParam(value: string | undefined): boolean { return value === "1" || value?.toLowerCase() === "true"; }

function parseVless(line: string, sourceId: string, sourceName: string): ParsedNode | null { const { body, remark } = splitHash(line); const rest = body.slice("vless://".length); const qIdx = rest.indexOf("?"); const main = qIdx === -1 ? rest : rest.slice(0, qIdx); const p = parseQuery(qIdx === -1 ? "" : rest.slice(qIdx + 1)); const at = main.lastIndexOf("@"); if (at === -1) return null; const uuid = decodeURIComponent(main.slice(0, at)).trim(); const hp = parseHostPort(main.slice(at + 1)); if (!hp) return null; const network = mapNetwork(p.type || p.network); const name = cleanRemark(remark || `${hp.host}:${hp.port}`); return { id: nodeId(["vless", hp.host, hp.port, uuid, network, p.path, p.security]), uri: line.trim(), protocol: "vless", name, host: hp.host, port: hp.port, country: countryFromRemark(remark + " " + name), sourceId, sourceName, uuid, security: p.security, network, flow: p.flow, sni: p.sni || p.servername, fp: p.fp, alpn: p.alpn, pbk: p.pbk, sid: p.sid, path: p.path, hostHeader: p.host, serviceName: p.serviceName || p.servicename, insecure: boolParam(p.insecure) || boolParam(p.allowInsecure), extra: p }; }
function parseTrojan(line: string, sourceId: string, sourceName: string): ParsedNode | null { const { body, remark } = splitHash(line); const rest = body.slice("trojan://".length); const qIdx = rest.indexOf("?"); const main = qIdx === -1 ? rest : rest.slice(0, qIdx); const p = parseQuery(qIdx === -1 ? "" : rest.slice(qIdx + 1)); const at = main.lastIndexOf("@"); if (at === -1) return null; const password = decodeURIComponent(main.slice(0, at)).trim(); const hp = parseHostPort(main.slice(at + 1)); if (!password || !hp) return null; const network = mapNetwork(p.type || p.network || "tcp"); const name = cleanRemark(remark || `${hp.host}:${hp.port}`); return { id: nodeId(["trojan", hp.host, hp.port, password, network]), uri: line.trim(), protocol: "trojan", name, host: hp.host, port: hp.port, country: countryFromRemark(remark + " " + name), sourceId, sourceName, password, security: p.security || "tls", network, sni: p.sni || p.peer, fp: p.fp, alpn: p.alpn, pbk: p.pbk, sid: p.sid, path: p.path, hostHeader: p.host, insecure: boolParam(p.insecure) || boolParam(p.allowInsecure), extra: p }; }
function parseHysteria2(line: string, sourceId: string, sourceName: string): ParsedNode | null { const { body, remark } = splitHash(line); const scheme = body.startsWith("hy2://") ? "hy2://" : "hysteria2://"; const rest = body.slice(scheme.length); const qIdx = rest.indexOf("?"); const main = qIdx === -1 ? rest : rest.slice(0, qIdx); const p = parseQuery(qIdx === -1 ? "" : rest.slice(qIdx + 1)); const at = main.lastIndexOf("@"); if (at === -1) return null; const password = decodeURIComponent(main.slice(0, at)).trim(); const hp = parseHostPort(main.slice(at + 1)); if (!hp || !password) return null; const name = cleanRemark(remark || `${hp.host}:${hp.port}`); return { id: nodeId(["hysteria2", hp.host, hp.port, password]), uri: line.trim().replace(/^hy2:\/\//, "hysteria2://"), protocol: "hysteria2", name, host: hp.host, port: hp.port, country: countryFromRemark(remark + " " + name), sourceId, sourceName, password, sni: p.sni || p.peer, insecure: boolParam(p.insecure), extra: p }; }
function parseTuic(line: string, sourceId: string, sourceName: string): ParsedNode | null { const { body, remark } = splitHash(line); const rest = body.slice("tuic://".length); const qIdx = rest.indexOf("?"); const main = qIdx === -1 ? rest : rest.slice(0, qIdx); const p = parseQuery(qIdx === -1 ? "" : rest.slice(qIdx + 1)); const at = main.lastIndexOf("@"); if (at === -1) return null; const userinfo = main.slice(0, at); const hp = parseHostPort(main.slice(at + 1)); if (!hp) return null; const [uuid, password] = userinfo.split(":").map((x) => x.trim()); if (!uuid || !password) return null; const name = cleanRemark(remark || `${hp.host}:${hp.port}`); return { id: nodeId(["tuic", hp.host, hp.port, uuid, password]), uri: line.trim(), protocol: "tuic", name, host: hp.host, port: hp.port, country: countryFromRemark(remark + " " + name), sourceId, sourceName, uuid, password, sni: p.sni, alpn: p.alpn, insecure: boolParam(p.insecure), extra: p }; }
function parseSs(line: string, sourceId: string, sourceName: string): ParsedNode | null { const { body, remark } = splitHash(line); let rest = body.slice("ss://".length); let method = ""; let password = ""; let authority = ""; if (rest.includes("@")) { const at = rest.lastIndexOf("@"); const userinfo = rest.slice(0, at); authority = rest.slice(at + 1); if (userinfo.includes(":")) { const colon = userinfo.indexOf(":"); method = decodeURIComponent(userinfo.slice(0, colon)).trim(); password = decodeURIComponent(userinfo.slice(colon + 1)).trim(); } else { const decoded = tryB64(userinfo); if (decoded?.includes(":")) { const colon = decoded.indexOf(":"); method = decoded.slice(0, colon).trim(); password = decoded.slice(colon + 1).trim(); } } } else { const decoded = tryB64(rest); if (!decoded) return null; const at = decoded.lastIndexOf("@"); if (at === -1) return null; const userinfo = decoded.slice(0, at); authority = decoded.slice(at + 1); const colon = userinfo.indexOf(":"); if (colon === -1) return null; method = userinfo.slice(0, colon).trim(); password = userinfo.slice(colon + 1).trim(); } const qIdx = authority.indexOf("?"); if (qIdx !== -1) authority = authority.slice(0, qIdx); const hp = parseHostPort(authority); if (!hp || !method || !password) return null; const name = cleanRemark(remark || `${hp.host}:${hp.port}`); return { id: nodeId(["ss", hp.host, hp.port, method, password]), uri: line.trim(), protocol: "ss", name, host: hp.host, port: hp.port, country: countryFromRemark(remark + " " + name), sourceId, sourceName, method, password, extra: {} }; }
function parseVmess(line: string, sourceId: string, sourceName: string): ParsedNode | null { const decoded = tryB64(line.slice("vmess://".length)); if (!decoded) return null; try { const j = JSON.parse(decoded) as Record<string, unknown>; const host = String(j.add || j.host || "").trim(); const port = Number(j.port); const uuid = String(j.id || "").trim(); if (!host || !port || !uuid) return null; const remark = String(j.ps || j.remark || `${host}:${port}`).trim(); const name = cleanRemark(remark); const network = mapNetwork(String(j.net || "tcp")); const tls = String(j.tls || "").trim(); const path = String(j.path || "").trim(); const hostHeader = String(j.host || "").trim(); const insecure = j.allowInsecure === true || String(j.allowInsecure || "").trim().toLowerCase() === "true" || String(j.insecure || "").trim() === "1"; return { id: nodeId(["vmess", host, port, uuid, network, path]), uri: line.trim(), protocol: "vmess", name, host, port, country: countryFromRemark(remark), sourceId, sourceName, uuid, aid: String(j.aid ?? "0").trim(), security: tls ? "tls" : "none", network, sni: String(j.sni || j.host || "").trim(), path, hostHeader, insecure, extra: { scy: String(j.scy || j.security || "auto").trim(), tls, type: String(j.type || "").trim(), packetEncoding: String(j.packetEncoding || "").trim() }; } catch { return null; } }

function sanitizeNode(node: ParsedNode): ParsedNode | null {
  const copy = { ...node } as ParsedNode;
  for (const key of ["uri", "name", "host", "sourceId", "sourceName", "uuid", "password", "method", "security", "network", "flow", "sni", "fp", "pbk", "sid", "path", "hostHeader", "serviceName", "aid"] as const) { const value = copy[key]; if (typeof value === "string") copy[key] = value.trim() as never; }
  copy.protocol = copy.protocol.trim().toLowerCase() as VpnProtocol;
  if (!PROTOCOLS.has(copy.protocol) || !copy.host || !Number.isInteger(copy.port) || copy.port < 1 || copy.port > 65535) return null;
  copy.network = mapNetwork(copy.network);
  if (!NETWORKS.has(copy.network)) return null;
  const alpn = (copy.alpn ?? "").split(",").map((x) => x.trim()).filter((x) => x.length > 0 && x.length <= 32 && ALPN_ALLOWED.has(x));
  copy.alpn = alpn.length ? alpn.join(",") : undefined;
  copy.extra = Object.fromEntries(Object.entries(copy.extra ?? {}).map(([k, v]) => [k.trim(), String(v).trim()]));
  if (copy.network === "ws" && !copy.path?.trim()) return null;
  if (copy.network === "grpc" && !copy.serviceName?.trim()) return null;
  if (copy.network === "xhttp" && !copy.path?.trim()) return null;
  if (["vless", "vmess", "tuic"].includes(copy.protocol) && !copy.uuid) return null;
  if (copy.protocol === "ss" && (!copy.password || !copy.method)) return null;
  if (["trojan", "hysteria2"].includes(copy.protocol) && !copy.password) return null;
  copy.id = nodeId([copy.protocol, copy.host, copy.port, copy.uuid, copy.password, copy.method, copy.network, copy.path, copy.security]);
  return copy;
}
export function parseUriLine(line: string, sourceId: string, sourceName: string): ParsedNode | null { const trimmed = decodeHtml(line.trim()); if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("//")) return null; const lower = trimmed.toLowerCase(); try { if (lower.startsWith("vless://")) return sanitizeNode(parseVless(trimmed, sourceId, sourceName)); if (lower.startsWith("vmess://")) return sanitizeNode(parseVmess(trimmed, sourceId, sourceName)); if (lower.startsWith("ss://")) return sanitizeNode(parseSs(trimmed, sourceId, sourceName)); if (lower.startsWith("trojan://")) return sanitizeNode(parseTrojan(trimmed, sourceId, sourceName)); if (lower.startsWith("hysteria2://") || lower.startsWith("hy2://")) return sanitizeNode(parseHysteria2(trimmed, sourceId, sourceName)); if (lower.startsWith("tuic://")) return sanitizeNode(parseTuic(trimmed, sourceId, sourceName)); } catch { return null; } return null; }
export function parseSubscription(raw: string, sourceId: string, sourceName: string): ParsedNode[] { let text = raw.replace(/^\uFEFF/, "").trim(); const maybe = tryB64(text); if (maybe && PROTO_RE.test(maybe.trim().split(/\r?\n/)[0] ?? "")) text = maybe; const nodes: ParsedNode[] = []; const seen = new Set<string>(); for (const line of text.split(/\r?\n/)) { const node = parseUriLine(line, sourceId, sourceName); if (!node || seen.has(node.id)) continue; seen.add(node.id); nodes.push(node); } return nodes; }
export function endpointKey(node: { host: string; port: number }): string { return `${node.host.toLowerCase()}:${node.port}`; }
export function protocolRank(p: VpnProtocol): number { return ({ vless: 1, vmess: 2, trojan: 3, ss: 4, hysteria2: 5, tuic: 6 })[p] ?? 99; }
